### PR TITLE
Default sandbox flag to nil in Rails 5.1

### LINKED ISSUE #4: Auto-sandboxing on environment does not work in Rails 5.1
With changes to how arguments are handled in Rails 5.1, `options[:sandbox]` now defaults to `false` so we cannot rely on it being `nil` when no `--sandbox` or `--no-sandbox` flag is passed.

### PR DESCRIPTION
**Pull request by timothysu**
This fixes #4 , as we rely on non-explicit enable/disablement of the sandbox (no `--sandbox` nor `--no-sandbox`) to automatically sandbox environments.

prime: @skarger

### CODE REVIEW

File: lib/safer_rails_console/patches/boot/sandbox_flag.rb [hunk 1]
```diff
@@ -76,6 +76,13 @@ def parse_arguments(arguments)
 elsif SaferRailsConsole::RailsVersion.five_zero?
   require 'rails/commands/commands_tasks'
   ::Rails::CommandsTasks.prepend(SaferRailsConsole::Patches::Boot::SandboxFlag::Rails::CommandsTasks50)
+elsif SaferRailsConsole::RailsVersion.five_one?
+  require 'rails/command'
+  require 'rails/commands/console/console_command'
+  ::Rails::Command::ConsoleCommand.class_eval do
```
Comment (timothysu) [inline lib/safer_rails_console/patches/boot/sandbox_flag.rb]: We want it to be `nil` to know if the user explicitly specifies `--sandbox` (`true`), `--no-sandbox` (`false`), or does not not pass a flag at all (`nil`).  We use this to enforce automatically specified rules (auto-sandbox).  I'll add a comment explaining this.
