### PR TITLE
Patch PostgreSQLAdapter#execute_and_clear instead of AbstractAdapter#log for auto-rollback

### LINKED ISSUE #13: safer_rails_console doesn't work in alerts service rails console mode in sandbox mode
Here's the output of my session:

```
jturkel:~/salsify/dandelion → feature/independent-client-jobs $ heroku run rails console -a alerts-service-prod
Running rails console on ⬢ alerts-service-prod... up, run.3086 (Standard-1X)
WARNING: YOU ARE USING RAILS CONSOLE IN PRODUCTION!
Changing data can cause serious data loss. Make sure you know what you're doing.
Loading production environment in sandbox (Rails 5.0.5)
Any modifications you make will be rolled back on exit
alerts-service(prod)(sandboxed):001:0> alert1 = Alerts::Alert.unscoped.find('s-bb81c329-571f-449b-84c6-2b995f02ca76')
ArgumentError: wrong number of arguments (given 5, expected 1..4)
  from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/sandbox/auto_rollback.rb:8:in `log'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:605:in `exec_cache'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/querying.rb:39:in `find_by_sql'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:702:in `exec_queries'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:583:in `load'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation.rb:260:in `records'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:527:in `find_take'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:100:in `take'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:477:in `find_one'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:458:in `find_with_ids'
  from /app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/relation/finder_methods.rb:66:in `find'
  from (irb):1
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/console.rb:65:in `start'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/console_helper.rb:9:in `start'
  from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/railtie/sandbox.rb:16:in `start'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:78:in `console'
  from /app/vendor/bundle/ruby/2.4.0/gems/safer_rails_console-0.1.2/lib/safer_rails_console/patches/boot/sandbox_flag.rb:47:in `console'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/commands.rb:18:in `<top (required)>'
  from /app/bin/rails:9:in `require'
  from /app/bin/rails:9:in `<main>'
```
The same query works fine when not run in sandbox mode.

### LINKED ISSUE #16: Invalid cached and prepared statements do not trigger a automatic rollback with PostgreSQL
`Model.first` triggers a rollback, however `Model.where('invalid statement')` does not which ends up poisoning the transaction.

### PR DESCRIPTION
**Pull request by timothysu**
This fixes #13 and fixes #16 , where auto-rollback was broken in certain Rails 5+ environments and auto-rollback did not work on specific commands.  This PR changes the patch so it is now focused on `PostgreSQLAdapter` instead of `AbstractAdapter`, as auto-rollback is only needed for postgres.

prime: @skarger

### CODE REVIEW

File: lib/safer_rails_console/patches/sandbox/auto_rollback.rb [hunk 1]
```diff
@@ -4,9 +4,20 @@ module Sandbox
...
-            module AbstractAdapter
+            module AbstractAdapter4
               def log(sql, name = 'SQL', binds = [], statement_name = nil)
-                super(sql, name, binds, statement_name) { yield }
+                super
+              rescue => e
+                connection = ::ActiveRecord::Base.connection
+                connection.rollback_db_transaction
+                connection.begin_db_transaction
+                raise e
```
Comment (skarger) [inline lib/safer_rails_console/patches/sandbox/auto_rollback.rb]: Consider extracting these 4 lines into a method like `rollback_and_begin_new_transaction!` that you can use in both `AbstractAdapter` versions.

**Comment by timothysu** [comment]
@skarger ready for another pass.  this morphed into something a little different so let me know if there are any questions.
